import type { CompanyRecord } from "@/ingest/types";

const today = "2026-03-30";

export const realTargets: CompanyRecord[] = [
  {
    company_id: "zapier",
    company_name: "Zapier",
    website: "https://zapier.com",
    headquarters: "Remote / United States",
    founding_year: 2011,
    employee_count: null,
    ownership_type: "private",
    industry_category: "ai_workflow",
    product_summary:
      "Automation platform connecting AI tools and thousands of business apps to orchestrate workflows, agents, and operational tasks.",
    customer_summary:
      "SMB through enterprise teams automating lead routing, internal operations, and customer-facing workflows across large SaaS stacks.",
    sales_motion: "mixed",
    annual_revenue_usd: 310000000,
    revenue_growth_yoy_pct: 19,
    gross_margin_pct: 84,
    burn_multiple: 0.9,
    net_retention_pct: 108,
    logo_churn_pct: 9,
    cash_months_remaining: 24,
    debt_to_revenue_ratio: 0.12,
    funding_stage: "Late stage private",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://zapier.com/"],
    source_market: ["official-website"],
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
  {
    company_id: "workato",
    company_name: "Workato",
    website: "https://www.workato.com",
    headquarters: "Mountain View, CA",
    founding_year: 2013,
    employee_count: null,
    ownership_type: "private",
    industry_category: "ai_workflow",
    product_summary:
      "Enterprise orchestration platform for apps, data, APIs, and AI agents built around integration and workflow execution.",
    customer_summary:
      "Enterprise IT, operations, and line-of-business teams standardizing automation and governed agent orchestration across systems.",
    sales_motion: "enterprise",
    annual_revenue_usd: 260000000,
    revenue_growth_yoy_pct: 24,
    gross_margin_pct: 78,
    burn_multiple: 1.2,
    net_retention_pct: 115,
    logo_churn_pct: 6,
    cash_months_remaining: 20,
    debt_to_revenue_ratio: 0.18,
    funding_stage: "Late stage private",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://www.workato.com/"],
    source_market: ["official-website"],
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
  {
    company_id: "intercom",
    company_name: "Intercom",
    website: "https://www.intercom.com",
    headquarters: "San Francisco, CA",
    founding_year: 2011,
    employee_count: null,
    ownership_type: "private",
    industry_category: "service_ops",
    product_summary:
      "AI-first customer service platform combining helpdesk, support workflows, and AI agents for customer conversations.",
    customer_summary:
      "Customer support and success teams modernizing service operations with AI-assisted and AI-led support workflows.",
    sales_motion: "mixed",
    annual_revenue_usd: 340000000,
    revenue_growth_yoy_pct: 17,
    gross_margin_pct: 79,
    burn_multiple: 1.1,
    net_retention_pct: 110,
    logo_churn_pct: 8,
    cash_months_remaining: 18,
    debt_to_revenue_ratio: 0.25,
    funding_stage: "Late stage private",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://www.intercom.com/"],
    source_market: ["official-website"],
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
  {
    company_id: "gong",
    company_name: "Gong",
    website: "https://www.gong.io/en",
    headquarters: "San Francisco, CA",
    founding_year: 2015,
    employee_count: null,
    ownership_type: "private",
    industry_category: "crm_adjacency",
    product_summary:
      "Revenue AI platform for sales, forecasting, deal inspection, and GTM execution built on conversation and account data.",
    customer_summary:
      "Revenue organizations and enterprise GTM teams seeking higher productivity, forecast confidence, and pipeline visibility.",
    sales_motion: "enterprise",
    annual_revenue_usd: 285000000,
    revenue_growth_yoy_pct: 23,
    gross_margin_pct: 82,
    burn_multiple: 1.4,
    net_retention_pct: 114,
    logo_churn_pct: 7,
    cash_months_remaining: 16,
    debt_to_revenue_ratio: 0.21,
    funding_stage: "Late stage private",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://www.gong.io/en"],
    source_market: ["official-website"],
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
  {
    company_id: "outreach",
    company_name: "Outreach",
    website: "https://www.outreach.io",
    headquarters: "Seattle, WA",
    founding_year: 2014,
    employee_count: null,
    ownership_type: "private",
    industry_category: "crm_adjacency",
    product_summary:
      "Sales execution and revenue workflow platform helping teams manage prospecting, deal progression, and rep productivity.",
    customer_summary:
      "B2B sales organizations and revenue operations teams standardizing outbound and opportunity execution workflows.",
    sales_motion: "enterprise",
    annual_revenue_usd: 240000000,
    revenue_growth_yoy_pct: 14,
    gross_margin_pct: 77,
    burn_multiple: 2.1,
    net_retention_pct: 107,
    logo_churn_pct: 10,
    cash_months_remaining: 14,
    debt_to_revenue_ratio: 0.33,
    funding_stage: "Late stage private",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://www.outreach.io/"],
    source_market: ["official-website"],
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
  {
    company_id: "talkdesk",
    company_name: "Talkdesk",
    website: "https://www.talkdesk.com",
    headquarters: "Palo Alto, CA",
    founding_year: 2011,
    employee_count: null,
    ownership_type: "private",
    industry_category: "service_ops",
    product_summary:
      "Customer experience automation platform using AI agents to orchestrate service and contact center workflows across the customer journey.",
    customer_summary:
      "Enterprises running complex customer support, contact center, and service operations across multiple channels.",
    sales_motion: "enterprise",
    annual_revenue_usd: 190000000,
    revenue_growth_yoy_pct: 18,
    gross_margin_pct: 72,
    burn_multiple: 1.8,
    net_retention_pct: 109,
    logo_churn_pct: 9,
    cash_months_remaining: 15,
    debt_to_revenue_ratio: 0.42,
    funding_stage: "Late stage private",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://www.talkdesk.com/"],
    source_market: ["official-website"],
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
  {
    company_id: "dataiku",
    company_name: "Dataiku",
    website: "https://www.dataiku.com/product",
    headquarters: "New York, NY",
    founding_year: 2013,
    employee_count: null,
    ownership_type: "private",
    industry_category: "developer_tooling",
    product_summary:
      "Enterprise AI platform bringing analytics, models, orchestration, governance, and AI agents into one governed system.",
    customer_summary:
      "Large enterprises operationalizing AI programs with governance, multi-team collaboration, and production deployment needs.",
    sales_motion: "enterprise",
    annual_revenue_usd: 210000000,
    revenue_growth_yoy_pct: 21,
    gross_margin_pct: 81,
    burn_multiple: 1.5,
    net_retention_pct: 113,
    logo_churn_pct: 7,
    cash_months_remaining: 18,
    debt_to_revenue_ratio: 0.2,
    funding_stage: "Late stage private",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://www.dataiku.com/product"],
    source_market: ["official-website"],
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
  {
    company_id: "hex",
    company_name: "Hex",
    website: "https://hex.tech",
    headquarters: "San Francisco, CA",
    founding_year: 2019,
    employee_count: null,
    ownership_type: "private",
    industry_category: "developer_tooling",
    product_summary:
      "Collaborative data and analytics workspace for notebooks, apps, models, and decision workflows used by technical teams.",
    customer_summary:
      "Data, analytics, and technical business teams building internal workflows and sharing governed analysis across the enterprise.",
    sales_motion: "mid_market",
    annual_revenue_usd: 32000000,
    revenue_growth_yoy_pct: 31,
    gross_margin_pct: 79,
    burn_multiple: 2.0,
    net_retention_pct: 118,
    logo_churn_pct: 8,
    cash_months_remaining: 16,
    debt_to_revenue_ratio: 0.15,
    funding_stage: "Series C",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://hex.tech"],
    source_market: ["official-website"],
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
  {
    company_id: "servicetitan",
    company_name: "ServiceTitan",
    website: "https://www.servicetitan.com",
    headquarters: "Glendale, CA",
    founding_year: 2012,
    employee_count: null,
    ownership_type: "public",
    industry_category: "vertical_saas",
    product_summary:
      "Vertical software platform for trade and field service businesses covering scheduling, operations, customer engagement, and revenue workflows.",
    customer_summary:
      "Field service and trades businesses modernizing dispatch, service operations, and customer interactions with vertical workflows.",
    sales_motion: "mixed",
    annual_revenue_usd: 780000000,
    revenue_growth_yoy_pct: 26,
    gross_margin_pct: 74,
    burn_multiple: 1.0,
    net_retention_pct: 117,
    logo_churn_pct: 5,
    cash_months_remaining: 24,
    debt_to_revenue_ratio: 0.1,
    funding_stage: "Public",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://www.servicetitan.com"],
    source_market: ["official-website"],
    financial_as_of: null,
    financial_provenance: {
      baseline: "Baseline fixture values are replaced by the public-company override layer when real-company mode runs.",
    },
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
  {
    company_id: "mews",
    company_name: "Mews",
    website: "https://www.mews.com",
    headquarters: "Amsterdam, Netherlands",
    founding_year: 2012,
    employee_count: null,
    ownership_type: "private",
    industry_category: "vertical_saas",
    product_summary:
      "Hospitality operations platform for reservations, guest journeys, payments, and property workflows with automation across service processes.",
    customer_summary:
      "Hospitality operators seeking modern vertical software with operational automation and customer experience workflows.",
    sales_motion: "mixed",
    annual_revenue_usd: 85000000,
    revenue_growth_yoy_pct: 27,
    gross_margin_pct: 70,
    burn_multiple: 1.7,
    net_retention_pct: 112,
    logo_churn_pct: 8,
    cash_months_remaining: 17,
    debt_to_revenue_ratio: 0.28,
    funding_stage: "Late stage private",
    total_funding_usd: null,
    last_round_date: null,
    last_round_post_money_usd: null,
    source_financials: ["assignment-estimate", "public-company-profile"],
    source_product: ["https://www.mews.com"],
    source_market: ["official-website"],
    data_quality_flags: ["estimated-financials", "real-company-profile"],
    collected_at: today,
  },
];
