import type { CompanyRecord } from "@/ingest/types";

const today = "2026-03-30";

export const sampleTargets: CompanyRecord[] = [
  {
    company_id: "agentflow-systems",
    company_name: "AgentFlow Systems",
    website: "https://agentflow.example.com",
    headquarters: "San Francisco, CA",
    founding_year: 2020,
    employee_count: 180,
    ownership_type: "private",
    industry_category: "ai_workflow",
    product_summary: "Agentic workflow automation software for enterprise support and back-office operations teams.",
    customer_summary: "Large enterprises modernizing internal operations and customer service workflows.",
    sales_motion: "enterprise",
    annual_revenue_usd: 18000000,
    revenue_growth_yoy_pct: 32,
    gross_margin_pct: 68,
    burn_multiple: 1.7,
    net_retention_pct: 118,
    logo_churn_pct: 8,
    cash_months_remaining: 16,
    debt_to_revenue_ratio: 0.25,
    funding_stage: "Series B",
    total_funding_usd: 62000000,
    last_round_date: "2025-09-15",
    last_round_post_money_usd: 250000000,
    source_financials: ["management-estimate", "board-deck"],
    source_product: ["website", "sales-notes"],
    source_market: ["analyst-memo"],
    data_quality_flags: [],
    collected_at: today,
  },
  {
    company_id: "custoweave",
    company_name: "CustoWeave",
    website: "https://custoweave.example.com",
    headquarters: "New York, NY",
    founding_year: 2018,
    employee_count: 240,
    ownership_type: "private",
    industry_category: "crm_adjacency",
    product_summary: "Customer data unification and enrichment layer used by revenue teams to orchestrate account workflows.",
    customer_summary: "Mid-market and enterprise revenue teams with fragmented customer-data stacks.",
    sales_motion: "mixed",
    annual_revenue_usd: 26000000,
    revenue_growth_yoy_pct: 28,
    gross_margin_pct: 71,
    burn_multiple: 1.4,
    net_retention_pct: 121,
    logo_churn_pct: 7,
    cash_months_remaining: 20,
    debt_to_revenue_ratio: 0.18,
    funding_stage: "Series C",
    total_funding_usd: 90000000,
    last_round_date: "2025-04-22",
    last_round_post_money_usd: 420000000,
    source_financials: ["management-estimate", "finance-model"],
    source_product: ["website", "demo-notes"],
    source_market: ["channel-checks"],
    data_quality_flags: [],
    collected_at: today,
  },
  {
    company_id: "servicelattice",
    company_name: "ServiceLattice",
    website: "https://servicelattice.example.com",
    headquarters: "Chicago, IL",
    founding_year: 2017,
    employee_count: 130,
    ownership_type: "private",
    industry_category: "service_ops",
    product_summary: "AI-assisted service operations platform for field service scheduling, resolution workflows, and knowledge routing.",
    customer_summary: "Enterprise service organizations in telecom, utilities, and industrial services.",
    sales_motion: "enterprise",
    annual_revenue_usd: 12000000,
    revenue_growth_yoy_pct: 19,
    gross_margin_pct: 58,
    burn_multiple: 1.9,
    net_retention_pct: 106,
    logo_churn_pct: 11,
    cash_months_remaining: 11,
    debt_to_revenue_ratio: 0.62,
    funding_stage: "Series A",
    total_funding_usd: 28000000,
    last_round_date: "2024-12-02",
    last_round_post_money_usd: 85000000,
    source_financials: ["management-estimate"],
    source_product: ["website", "product-brief"],
    source_market: ["industry-note"],
    data_quality_flags: [],
    collected_at: today,
  },
  {
    company_id: "devrelay",
    company_name: "DevRelay",
    website: "https://devrelay.example.com",
    headquarters: "Austin, TX",
    founding_year: 2021,
    employee_count: 95,
    ownership_type: "private",
    industry_category: "developer_tooling",
    product_summary: "Developer workflow and orchestration tooling that helps teams operationalize agents and internal copilots.",
    customer_summary: "Platform and developer-experience teams inside large software companies.",
    sales_motion: "enterprise",
    annual_revenue_usd: 9500000,
    revenue_growth_yoy_pct: 24,
    gross_margin_pct: 61,
    burn_multiple: 2.1,
    net_retention_pct: 112,
    logo_churn_pct: 9,
    cash_months_remaining: 13,
    debt_to_revenue_ratio: 0.8,
    funding_stage: "Series A",
    total_funding_usd: 21000000,
    last_round_date: "2025-06-11",
    last_round_post_money_usd: 95000000,
    source_financials: ["management-estimate"],
    source_product: ["website", "technical-due-diligence"],
    source_market: ["customer-calls"],
    data_quality_flags: [],
    collected_at: today,
  },
  {
    company_id: "verticalforge-health",
    company_name: "VerticalForge Health",
    website: "https://verticalforge.example.com",
    headquarters: "Boston, MA",
    founding_year: 2016,
    employee_count: 310,
    ownership_type: "private",
    industry_category: "vertical_saas",
    product_summary: "Healthcare operations software with embedded workflow automation for intake, scheduling, and patient communications.",
    customer_summary: "Regional health systems and specialty clinic networks.",
    sales_motion: "enterprise",
    annual_revenue_usd: 42000000,
    revenue_growth_yoy_pct: 22,
    gross_margin_pct: 64,
    burn_multiple: 1.2,
    net_retention_pct: 109,
    logo_churn_pct: 6,
    cash_months_remaining: 18,
    debt_to_revenue_ratio: 0.35,
    funding_stage: "Series C",
    total_funding_usd: 120000000,
    last_round_date: "2025-01-07",
    last_round_post_money_usd: 550000000,
    source_financials: ["management-estimate", "finance-model"],
    source_product: ["website", "sales-notes"],
    source_market: ["vertical-analyst-note"],
    data_quality_flags: [],
    collected_at: today,
  },
  {
    company_id: "signalnest",
    company_name: "SignalNest",
    website: "https://signalnest.example.com",
    headquarters: "Seattle, WA",
    founding_year: 2022,
    employee_count: 70,
    ownership_type: "private",
    industry_category: "crm_adjacency",
    product_summary: "AI signal aggregation for account teams with automated next-best-action prompts.",
    customer_summary: "High-growth B2B companies with lean revenue operations teams.",
    sales_motion: "mid_market",
    annual_revenue_usd: 4300000,
    revenue_growth_yoy_pct: 38,
    gross_margin_pct: 74,
    burn_multiple: 2.4,
    net_retention_pct: 114,
    logo_churn_pct: 10,
    cash_months_remaining: 14,
    debt_to_revenue_ratio: 0.22,
    funding_stage: "Seed",
    total_funding_usd: 7000000,
    last_round_date: "2025-10-03",
    last_round_post_money_usd: 35000000,
    source_financials: ["management-estimate"],
    source_product: ["website"],
    source_market: ["customer-call"],
    data_quality_flags: [],
    collected_at: today,
  },
  {
    company_id: "opsharbor",
    company_name: "OpsHarbor",
    website: "https://opsharbor.example.com",
    headquarters: "Denver, CO",
    founding_year: 2019,
    employee_count: 120,
    ownership_type: "private",
    industry_category: "service_ops",
    product_summary: "Operations workflow system for service teams with AI-assisted dispatch and exception handling.",
    customer_summary: "Mid-market and enterprise service organizations with complex field operations.",
    sales_motion: "mixed",
    annual_revenue_usd: 11000000,
    revenue_growth_yoy_pct: 14,
    gross_margin_pct: 63,
    burn_multiple: 1.8,
    net_retention_pct: 108,
    logo_churn_pct: 12,
    cash_months_remaining: 10,
    debt_to_revenue_ratio: 0.55,
    funding_stage: "Series A",
    total_funding_usd: 24000000,
    last_round_date: "2024-08-20",
    last_round_post_money_usd: 78000000,
    source_financials: ["management-estimate"],
    source_product: ["website", "demo-notes"],
    source_market: ["industry-memo"],
    data_quality_flags: [],
    collected_at: today,
  },
  {
    company_id: "gridpilot",
    company_name: "GridPilot",
    website: "https://gridpilot.example.com",
    headquarters: "Atlanta, GA",
    founding_year: 2018,
    employee_count: 85,
    ownership_type: "private",
    industry_category: "other",
    product_summary: "Optimization software for energy procurement teams with limited connection to Salesforce product surfaces.",
    customer_summary: "Procurement teams in energy-intensive industries.",
    sales_motion: "enterprise",
    annual_revenue_usd: 16000000,
    revenue_growth_yoy_pct: 27,
    gross_margin_pct: 66,
    burn_multiple: 1.5,
    net_retention_pct: 116,
    logo_churn_pct: 8,
    cash_months_remaining: 17,
    debt_to_revenue_ratio: 0.31,
    funding_stage: "Series B",
    total_funding_usd: 45000000,
    last_round_date: "2025-02-14",
    last_round_post_money_usd: 170000000,
    source_financials: ["management-estimate"],
    source_product: ["website", "product-brief"],
    source_market: ["market-note"],
    data_quality_flags: [],
    collected_at: today,
  },
  {
    company_id: "casehive",
    company_name: "CaseHive",
    website: "https://casehive.example.com",
    headquarters: "Los Angeles, CA",
    founding_year: 2020,
    employee_count: 150,
    ownership_type: "private",
    industry_category: "service_ops",
    product_summary: "Customer support knowledge and case orchestration platform with agentic resolution workflows.",
    customer_summary: "Service Cloud-heavy enterprises focused on support productivity.",
    sales_motion: "enterprise",
    annual_revenue_usd: 22000000,
    revenue_growth_yoy_pct: 31,
    gross_margin_pct: 69,
    burn_multiple: 1.6,
    net_retention_pct: 124,
    logo_churn_pct: 5,
    cash_months_remaining: 19,
    debt_to_revenue_ratio: 0.2,
    funding_stage: "Series B",
    total_funding_usd: 68000000,
    last_round_date: "2025-05-30",
    last_round_post_money_usd: 310000000,
    source_financials: ["management-estimate", "finance-model"],
    source_product: ["website", "demo-notes", "reference-call"],
    source_market: ["customer-calls"],
    data_quality_flags: [],
    collected_at: today,
  },
  {
    company_id: "relaystack",
    company_name: "RelayStack",
    website: "https://relaystack.example.com",
    headquarters: "Toronto, CA",
    founding_year: 2019,
    employee_count: 105,
    ownership_type: "private",
    industry_category: "developer_tooling",
    product_summary: "Platform tooling for orchestrating internal AI agents and workflow steps across enterprise systems.",
    customer_summary: "Enterprise IT and developer platform teams modernizing automation stacks.",
    sales_motion: "enterprise",
    annual_revenue_usd: 13000000,
    revenue_growth_yoy_pct: 29,
    gross_margin_pct: 54,
    burn_multiple: 3.4,
    net_retention_pct: 111,
    logo_churn_pct: 9,
    cash_months_remaining: 9,
    debt_to_revenue_ratio: 0.93,
    funding_stage: "Series A",
    total_funding_usd: 31000000,
    last_round_date: "2025-03-19",
    last_round_post_money_usd: 110000000,
    source_financials: ["management-estimate"],
    source_product: ["website", "technical-review"],
    source_market: ["customer-call"],
    data_quality_flags: [],
    collected_at: today,
  },
];
